/** @type {import('tailwindcss').Config} */ module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "flying-type": "#7c93e5",
        "flying-color": "#7186d0",
        "poison-type": "#e090f8",
        "poison-color": "#cc83e1",
        "fire-type": "#fc6c6d",
        "fire-color": "#e56263",
        "grass-type": "#49d0b0",
        "grass-color": "#42bda0",
        "water-type": "#70b6f9",
        "water-color": "#66a5e2",
        "bug-type": "#a0c888",
        "bug-color": "#91b67c",
        "normal-type": "#bcbdaf",
        "normal-color": "#abac9f",
        "electric-type": "#fcd46e",
        "electric-color": "#e5c164",
        "ground-type": "#e0c068",
        "ground-color": "#ccaf5f",
        "fairy-type": "#ff65d5",
        "fairy-color": "#e85cc2",
        "psychic-type": "#f838a8",
        "psychic-color": "#e13399",
        "fighting-type": "#f87070",
        "fighting-color": "#e16666",
        "rock-type": "#b8a038",
        "rock-color": "#a79133",
        "ghost-type": "#705898",
        "ghost-color": "#66508a",
        "ice-type": "#98d8d8",
        "ice-color": "#8ac4c4",
        "dragon-type": "#7038f8",
        "dragon-color": "#6633e1",
      },
      backgroundImage: {
        "poki-natuur": "url('/src/assets/pokemon-back.jpg')",
      },
    },
  },
  variants: {},
  plugins: [],
  plugins: [],
};
